# Generated by Django 2.1.7 on 2019-03-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(default='password', max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('roles', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='000', max_length=25)),
                ('section', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=25)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
    ]
