# Generated by Django 2.1.7 on 2019-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.CharField(default='0x1', max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
