# Generated by Django 2.1.7 on 2019-03-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190320_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.IntegerField(default='0x1', max_length=6),
        ),
    ]
