# Generated by Django 2.1.7 on 2019-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tacourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacourse',
            name='remaining_sections',
            field=models.IntegerField(default=0),
        ),
    ]
