# Generated by Django 2.1.7 on 2019-03-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tacourse_remaining_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacourse',
            name='assigned_ta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Account'),
        ),
    ]
