# Generated by Django 2.1.7 on 2019-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190321_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.IntegerField(default=1),
        ),
    ]
