# Generated by Django 2.1.7 on 2019-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190328_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacourse',
            name='remaining_sections',
            field=models.IntegerField(default=0),
        ),
    ]
