# Generated by Django 2.1.7 on 2019-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190322_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='password', max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
