# Generated by Django 2.1.7 on 2019-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190322_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='000', max_length=25, unique=True),
        ),
    ]
