from app.views.assign_ta_course import AssignTaCourse
from app.views.cr_account import CreateAccount
from app.views.dashboard import Dashboard
from app.views.edit_account import EditAccount
from app.views.login import Login
from app.views.logout import Logout
from app.views.update_contact import UpdateContactInfo
from app.views.view_accounts import ViewAccounts
from app.views.view_courses import ViewCourses
from app.views.my_courses import MyCourses
from app.views.assign_ins import AssignInstructor
